obj-$(CONFIG_ABI)               += util/
obj-$(CONFIG_ABI_SVR4)          += svr4/
obj-$(CONFIG_ABI_SCO)           += sco/ cxenix/
obj-$(CONFIG_ABI_WYSE)          += wyse/
obj-$(CONFIG_ABI_UW7)           += uw7/
obj-$(CONFIG_ABI_SOLARIS)       += solaris/
obj-$(CONFIG_ABI_IBCS)          += ibcs/
obj-$(CONFIG_ABI_ISC)           += isc/
